version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
        environment:
          GOFLAGS: -mod=vendor
    steps:
      - checkout
      - run: go test -v ./...
  lint:
    docker:
      - image: golangci/golangci-lint:v1.23.6-alpine
    steps:
      - checkout
      -run: golangci-lint run
  release:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: ./script/release
workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - lint
      - release:
          requires:
          - test
          - lint
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
