version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
        environment:
          GOFLAGS: -mod=vendor
    steps:
      - checkout
      - run: go test -v ./...
  lint:
    docker:
      - image: golangci/golangci-lint:v1.23.6-alpine
    steps:
      - checkout
      - run: golangci-lint run
  release:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: ./script/release
  build:
    docker:
      - image: docker:stable
    steps:
    - checkout
    - setup_remote_docker
    - run: docker build -t bakins/prometheus-http-discovery:${CIRCLE_TAG} .
  push:
    docker:
      - image: docker:stable
    steps:
    - checkout
    - setup_remote_docker
    - command: |
        echo ${DOCKER_TOKEN} | docker login --username=bakins --password-stdin
        docker push bakins/prometheus-http-discovery:${CIRCLE_TAG}

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - lint
      - build
      - push
      - release:
          requires:
          - test
          - lint
          - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - push:
          requires:
          - test
          - lint
          - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
