version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
        environment:
          GOFLAGS: -mod=vendor
    steps:
      - checkout
      - run: go test -mod=vendor -v ./...
  lint:
    docker:
      - image: golangci/golangci-lint:v1.23.6-alpine
    steps:
      - checkout
      - run: golangci-lint run
  release:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: ./script/release
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
    - checkout
    - setup_remote_docker
    - run: docker build -t bakins/prometheus-http-discovery:${CIRCLE_SHA1} .
  push:
    docker:
      - image: circleci/golang:1.14
    steps:
    - checkout
    - setup_remote_docker
    - run:
        command: |
          echo ${DOCKER_TOKEN} | docker login --username=bakins --password-stdin
          docker build -t bakins/prometheus-http-discovery:${CIRCLE_SHA1} .
          docker tag bakins/prometheus-http-discovery:${CIRCLE_SHA1} bakins/prometheus-http-discovery:${CIRCLE_TAG}
          docker push bakins/prometheus-http-discovery:${CIRCLE_TAG}

workflows:
  version: 2
  test:
    jobs:
      - test
      - lint
      - build
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - push:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
